# Generated by Django 5.0.7 on 2024-07-28 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='NONE', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='fullname',
            field=models.CharField(default='NONE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='NONE', max_length=12),
            preserve_default=False,
        ),
    ]
